/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './download.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '../../../app/download/download.component';
const styles_DownloadComponent:any[] = [import0.styles];
export const RenderType_DownloadComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_DownloadComponent,
  data: {}
}
);
export function View_DownloadComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h2',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Download']))
  ]
  ,(null as any),(null as any));
}
function View_DownloadComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_DownloadComponent_0,RenderType_DownloadComponent)),
    import1.ɵdid(114688,(null as any),0,import2.DownloadComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const DownloadComponentNgFactory:import1.ComponentFactory<import2.DownloadComponent> = import1.ɵccf('ng-component',import2.DownloadComponent,View_DownloadComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZG93bmxvYWQvZG93bmxvYWQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2dpdGh1Yi9nZXQtcGRmLW9ubGluZS9zcmMvUHJlY2l6ZVNvZnQuR2V0UGRmT25saW5lLldlYi5OZ0FwcC9zcmMvYXBwL2Rvd25sb2FkL2Rvd25sb2FkLmNvbXBvbmVudC50cyIsIm5nOi8vL0Q6L2dpdGh1Yi9nZXQtcGRmLW9ubGluZS9zcmMvUHJlY2l6ZVNvZnQuR2V0UGRmT25saW5lLldlYi5OZ0FwcC9zcmMvYXBwL2Rvd25sb2FkL2Rvd25sb2FkLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZG93bmxvYWQvZG93bmxvYWQuY29tcG9uZW50LnRzLkRvd25sb2FkQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGgyPkRvd25sb2FkPC9oMj4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFBSTs7Ozs7O0lDQUo7Z0JBQUE7OztJQUFBOzs7In0=
