/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/download/download.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../app/download/download-routing.module';
import * as import4 from './download.component.ngfactory';
import * as import5 from '../../../app/download/download.component';
class DownloadModuleInjector extends import0.ɵNgModuleInjector<import1.DownloadModule> {
  _RouterModule_0:import2.RouterModule;
  _DownloadRoutingModule_1:import3.DownloadRoutingModule;
  _DownloadModule_2:import1.DownloadModule;
  _ROUTES_3:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import4.DownloadComponentNgFactory],([] as any[]));
  }
  createInternal():import1.DownloadModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._DownloadRoutingModule_1 = new import3.DownloadRoutingModule();
    this._DownloadModule_2 = new import1.DownloadModule();
        this._ROUTES_3 = [[{
          path: '',
          component: import5.DownloadComponent
        }
    ]];
    return this._DownloadModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.DownloadRoutingModule)) { return this._DownloadRoutingModule_1; }
    if ((token === import1.DownloadModule)) { return this._DownloadModule_2; }
    if ((token === import2.ROUTES)) { return this._ROUTES_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DownloadModuleNgFactory:import0.NgModuleFactory<import1.DownloadModule> = new import0.NgModuleFactory<any>(DownloadModuleInjector,import1.DownloadModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZG93bmxvYWQvZG93bmxvYWQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2dpdGh1Yi9nZXQtcGRmLW9ubGluZS9zcmMvUHJlY2l6ZVNvZnQuR2V0UGRmT25saW5lLldlYi5OZ0FwcC9zcmMvYXBwL2Rvd25sb2FkL2Rvd25sb2FkLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
