/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9naXRodWIvZ2V0LXBkZi1vbmxpbmUvc3JjL1ByZWNpemVTb2Z0LkdldFBkZk9ubGluZS5XZWIuTmdBcHAvc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
