/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/about/about-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './about.component.ngfactory';
import * as import4 from '../../../app/about/about.component';
class AboutRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.AboutRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _AboutRoutingModule_1:import1.AboutRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.AboutComponentNgFactory],([] as any[]));
  }
  createInternal():import1.AboutRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._AboutRoutingModule_1 = new import1.AboutRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          component: import4.AboutComponent
        }
    ]];
    return this._AboutRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.AboutRoutingModule)) { return this._AboutRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AboutRoutingModuleNgFactory:import0.NgModuleFactory<import1.AboutRoutingModule> = new import0.NgModuleFactory<any>(AboutRoutingModuleInjector,import1.AboutRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvYWJvdXQvYWJvdXQtcm91dGluZy5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvYWJvdXQvYWJvdXQtcm91dGluZy5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
