/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/about/about.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../app/about/about-routing.module';
import * as import4 from './about.component.ngfactory';
import * as import5 from '../../../app/about/about.component';
class AboutModuleInjector extends import0.ɵNgModuleInjector<import1.AboutModule> {
  _RouterModule_0:import2.RouterModule;
  _AboutRoutingModule_1:import3.AboutRoutingModule;
  _AboutModule_2:import1.AboutModule;
  _ROUTES_3:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import4.AboutComponentNgFactory],([] as any[]));
  }
  createInternal():import1.AboutModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._AboutRoutingModule_1 = new import3.AboutRoutingModule();
    this._AboutModule_2 = new import1.AboutModule();
        this._ROUTES_3 = [[{
          path: '',
          component: import5.AboutComponent
        }
    ]];
    return this._AboutModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.AboutRoutingModule)) { return this._AboutRoutingModule_1; }
    if ((token === import1.AboutModule)) { return this._AboutModule_2; }
    if ((token === import2.ROUTES)) { return this._ROUTES_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AboutModuleNgFactory:import0.NgModuleFactory<import1.AboutModule> = new import0.NgModuleFactory<any>(AboutModuleInjector,import1.AboutModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvYWJvdXQvYWJvdXQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2dpdGh1Yi9nZXQtcGRmLW9ubGluZS9zcmMvUHJlY2l6ZVNvZnQuR2V0UGRmT25saW5lLldlYi5OZ0FwcC9zcmMvYXBwL2Fib3V0L2Fib3V0Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
