/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/statistics/statistics-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './statistics.component.ngfactory';
import * as import4 from '../../../app/statistics/statistics.component';
class StatisticsRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.StatisticsRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _StatisticsRoutingModule_1:import1.StatisticsRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.StatisticsComponentNgFactory],([] as any[]));
  }
  createInternal():import1.StatisticsRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._StatisticsRoutingModule_1 = new import1.StatisticsRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          component: import4.StatisticsComponent
        }
    ]];
    return this._StatisticsRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.StatisticsRoutingModule)) { return this._StatisticsRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const StatisticsRoutingModuleNgFactory:import0.NgModuleFactory<import1.StatisticsRoutingModule> = new import0.NgModuleFactory<any>(StatisticsRoutingModuleInjector,import1.StatisticsRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvc3RhdGlzdGljcy9zdGF0aXN0aWNzLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2dpdGh1Yi9nZXQtcGRmLW9ubGluZS9zcmMvUHJlY2l6ZVNvZnQuR2V0UGRmT25saW5lLldlYi5OZ0FwcC9zcmMvYXBwL3N0YXRpc3RpY3Mvc3RhdGlzdGljcy1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
