/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/statistics/statistics.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '../../../app/statistics/statistics-routing.module';
import * as import5 from '../../../app/statistics/shared/statistics.service';
import * as import6 from './statistics.component.ngfactory';
import * as import7 from '../../../app/statistics/statistics.component';
class StatisticsModuleInjector extends import0.ɵNgModuleInjector<import1.StatisticsModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _StatisticsRoutingModule_2:import4.StatisticsRoutingModule;
  _StatisticsModule_3:import1.StatisticsModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  _ROUTES_5:any[];
  __StatisticsService_6:import5.StatisticsService;
  constructor(parent:import0.Injector) {
    super(parent,[import6.StatisticsComponentNgFactory],([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  get _StatisticsService_6():import5.StatisticsService {
    if ((this.__StatisticsService_6 == null)) { (this.__StatisticsService_6 = new import5.StatisticsService()); }
    return this.__StatisticsService_6;
  }
  createInternal():import1.StatisticsModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ɵa,(null as any)),this.parent.get(import3.Router,(null as any)));
    this._StatisticsRoutingModule_2 = new import4.StatisticsRoutingModule();
    this._StatisticsModule_3 = new import1.StatisticsModule();
        this._ROUTES_5 = [[{
          path: '',
          component: import7.StatisticsComponent
        }
    ]];
    return this._StatisticsModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.StatisticsRoutingModule)) { return this._StatisticsRoutingModule_2; }
    if ((token === import1.StatisticsModule)) { return this._StatisticsModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.ROUTES)) { return this._ROUTES_5; }
    if ((token === import5.StatisticsService)) { return this._StatisticsService_6; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const StatisticsModuleNgFactory:import0.NgModuleFactory<import1.StatisticsModule> = new import0.NgModuleFactory<any>(StatisticsModuleInjector,import1.StatisticsModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvc3RhdGlzdGljcy9zdGF0aXN0aWNzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9naXRodWIvZ2V0LXBkZi1vbmxpbmUvc3JjL1ByZWNpemVTb2Z0LkdldFBkZk9ubGluZS5XZWIuTmdBcHAvc3JjL2FwcC9zdGF0aXN0aWNzL3N0YXRpc3RpY3MubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
