/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/developers/developers-use-offline.component';
const styles_DevelopersUseOfflineComponent:any[] = ([] as any[]);
export const RenderType_DevelopersUseOfflineComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_DevelopersUseOfflineComponent,
  data: {}
}
);
export function View_DevelopersUseOfflineComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Use offline']))
  ]
  ,(null as any),(null as any));
}
function View_DevelopersUseOfflineComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_DevelopersUseOfflineComponent_0,RenderType_DevelopersUseOfflineComponent)),
    import0.ɵdid(114688,(null as any),0,import1.DevelopersUseOfflineComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const DevelopersUseOfflineComponentNgFactory:import0.ComponentFactory<import1.DevelopersUseOfflineComponent> = import0.ɵccf('ng-component',import1.DevelopersUseOfflineComponent,View_DevelopersUseOfflineComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZGV2ZWxvcGVycy9kZXZlbG9wZXJzLXVzZS1vZmZsaW5lLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9naXRodWIvZ2V0LXBkZi1vbmxpbmUvc3JjL1ByZWNpemVTb2Z0LkdldFBkZk9ubGluZS5XZWIuTmdBcHAvc3JjL2FwcC9kZXZlbG9wZXJzL2RldmVsb3BlcnMtdXNlLW9mZmxpbmUuY29tcG9uZW50LnRzIiwibmc6Ly8vRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZGV2ZWxvcGVycy9kZXZlbG9wZXJzLXVzZS1vZmZsaW5lLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZGV2ZWxvcGVycy9kZXZlbG9wZXJzLXVzZS1vZmZsaW5lLmNvbXBvbmVudC50cy5EZXZlbG9wZXJzVXNlT2ZmbGluZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlVzZSBvZmZsaW5lPC9wPiIsIjxuZy1jb21wb25lbnQ+PC9uZy1jb21wb25lbnQ+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUc7Ozs7OztJQ0FIO2dCQUFBOzs7SUFBQTs7OyJ9
