/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/developers/developers.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../app/developers/developers-routing.module';
import * as import4 from './developers.component.ngfactory';
import * as import5 from './developers-overview.component.ngfactory';
import * as import6 from './developers-rest-api.component.ngfactory';
import * as import7 from './developers-soap-api.component.ngfactory';
import * as import8 from './developers-use-offline.component.ngfactory';
import * as import9 from './developers-net-libraries.component.ngfactory';
import * as import10 from './developers-source-code.component.ngfactory';
import * as import11 from '../../../app/developers/developers.component';
import * as import12 from '../../../app/developers/developers-overview.component';
import * as import13 from '../../../app/developers/developers-rest-api.component';
import * as import14 from '../../../app/developers/developers-soap-api.component';
import * as import15 from '../../../app/developers/developers-use-offline.component';
import * as import16 from '../../../app/developers/developers-net-libraries.component';
import * as import17 from '../../../app/developers/developers-source-code.component';
class DevelopersModuleInjector extends import0.ɵNgModuleInjector<import1.DevelopersModule> {
  _RouterModule_0:import2.RouterModule;
  _DevelopersRoutingModule_1:import3.DevelopersRoutingModule;
  _DevelopersModule_2:import1.DevelopersModule;
  _ROUTES_3:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import4.DevelopersComponentNgFactory,
      import5.DevelopersOverviewComponentNgFactory,
      import6.DevelopersRestApiComponentNgFactory,
      import7.DevelopersSoapApiComponentNgFactory,
      import8.DevelopersUseOfflineComponentNgFactory,
      import9.DevelopersNetLibrariesComponentNgFactory,
      import10.DevelopersSourceCodeComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.DevelopersModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._DevelopersRoutingModule_1 = new import3.DevelopersRoutingModule();
    this._DevelopersModule_2 = new import1.DevelopersModule();
        this._ROUTES_3 = [[{
          path: '',
          component: import11.DevelopersComponent,
          children: [
            {
              path: 'overview',
              component: import12.DevelopersOverviewComponent
            }
            ,
            {
              path: 'rest-api',
              component: import13.DevelopersRestApiComponent
            }
            ,
            {
              path: 'soap-api',
              component: import14.DevelopersSoapApiComponent
            }
            ,
            {
              path: 'use-offline',
              component: import15.DevelopersUseOfflineComponent
            }
            ,
            {
              path: 'net-libraries',
              component: import16.DevelopersNetLibrariesComponent
            }
            ,
            {
              path: 'source-code',
              component: import17.DevelopersSourceCodeComponent
            }
            ,
            {
              path: '**',
              redirectTo: 'overview'
            }

          ]

        }
    ]];
    return this._DevelopersModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.DevelopersRoutingModule)) { return this._DevelopersRoutingModule_1; }
    if ((token === import1.DevelopersModule)) { return this._DevelopersModule_2; }
    if ((token === import2.ROUTES)) { return this._ROUTES_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DevelopersModuleNgFactory:import0.NgModuleFactory<import1.DevelopersModule> = new import0.NgModuleFactory<any>(DevelopersModuleInjector,import1.DevelopersModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZGV2ZWxvcGVycy9kZXZlbG9wZXJzLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9naXRodWIvZ2V0LXBkZi1vbmxpbmUvc3JjL1ByZWNpemVTb2Z0LkdldFBkZk9ubGluZS5XZWIuTmdBcHAvc3JjL2FwcC9kZXZlbG9wZXJzL2RldmVsb3BlcnMubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
