/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/developers/developers-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './developers.component.ngfactory';
import * as import4 from './developers-overview.component.ngfactory';
import * as import5 from './developers-rest-api.component.ngfactory';
import * as import6 from './developers-soap-api.component.ngfactory';
import * as import7 from './developers-use-offline.component.ngfactory';
import * as import8 from './developers-net-libraries.component.ngfactory';
import * as import9 from './developers-source-code.component.ngfactory';
import * as import10 from '../../../app/developers/developers.component';
import * as import11 from '../../../app/developers/developers-overview.component';
import * as import12 from '../../../app/developers/developers-rest-api.component';
import * as import13 from '../../../app/developers/developers-soap-api.component';
import * as import14 from '../../../app/developers/developers-use-offline.component';
import * as import15 from '../../../app/developers/developers-net-libraries.component';
import * as import16 from '../../../app/developers/developers-source-code.component';
class DevelopersRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.DevelopersRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _DevelopersRoutingModule_1:import1.DevelopersRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.DevelopersComponentNgFactory,
      import4.DevelopersOverviewComponentNgFactory,
      import5.DevelopersRestApiComponentNgFactory,
      import6.DevelopersSoapApiComponentNgFactory,
      import7.DevelopersUseOfflineComponentNgFactory,
      import8.DevelopersNetLibrariesComponentNgFactory,
      import9.DevelopersSourceCodeComponentNgFactory
    ]
    ,([] as any[]));
  }
  createInternal():import1.DevelopersRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._DevelopersRoutingModule_1 = new import1.DevelopersRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          component: import10.DevelopersComponent,
          children: [
            {
              path: 'overview',
              component: import11.DevelopersOverviewComponent
            }
            ,
            {
              path: 'rest-api',
              component: import12.DevelopersRestApiComponent
            }
            ,
            {
              path: 'soap-api',
              component: import13.DevelopersSoapApiComponent
            }
            ,
            {
              path: 'use-offline',
              component: import14.DevelopersUseOfflineComponent
            }
            ,
            {
              path: 'net-libraries',
              component: import15.DevelopersNetLibrariesComponent
            }
            ,
            {
              path: 'source-code',
              component: import16.DevelopersSourceCodeComponent
            }
            ,
            {
              path: '**',
              redirectTo: 'overview'
            }

          ]

        }
    ]];
    return this._DevelopersRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.DevelopersRoutingModule)) { return this._DevelopersRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const DevelopersRoutingModuleNgFactory:import0.NgModuleFactory<import1.DevelopersRoutingModule> = new import0.NgModuleFactory<any>(DevelopersRoutingModuleInjector,import1.DevelopersRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvZGV2ZWxvcGVycy9kZXZlbG9wZXJzLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2dpdGh1Yi9nZXQtcGRmLW9ubGluZS9zcmMvUHJlY2l6ZVNvZnQuR2V0UGRmT25saW5lLldlYi5OZ0FwcC9zcmMvYXBwL2RldmVsb3BlcnMvZGV2ZWxvcGVycy1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
