/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/convert/convert.module';
import * as import2 from '@angular/router';
import * as import3 from '../../../app/convert/convert-routing.module';
import * as import4 from './convert.component.ngfactory';
import * as import5 from '../../../app/convert/convert.component';
class ConvertModuleInjector extends import0.ɵNgModuleInjector<import1.ConvertModule> {
  _RouterModule_0:import2.RouterModule;
  _ConvertRoutingModule_1:import3.ConvertRoutingModule;
  _ConvertModule_2:import1.ConvertModule;
  _ROUTES_3:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import4.ConvertComponentNgFactory],([] as any[]));
  }
  createInternal():import1.ConvertModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._ConvertRoutingModule_1 = new import3.ConvertRoutingModule();
    this._ConvertModule_2 = new import1.ConvertModule();
        this._ROUTES_3 = [[{
          path: '',
          component: import5.ConvertComponent
        }
    ]];
    return this._ConvertModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import3.ConvertRoutingModule)) { return this._ConvertRoutingModule_1; }
    if ((token === import1.ConvertModule)) { return this._ConvertModule_2; }
    if ((token === import2.ROUTES)) { return this._ROUTES_3; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ConvertModuleNgFactory:import0.NgModuleFactory<import1.ConvertModule> = new import0.NgModuleFactory<any>(ConvertModuleInjector,import1.ConvertModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvY29udmVydC9jb252ZXJ0Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9naXRodWIvZ2V0LXBkZi1vbmxpbmUvc3JjL1ByZWNpemVTb2Z0LkdldFBkZk9ubGluZS5XZWIuTmdBcHAvc3JjL2FwcC9jb252ZXJ0L2NvbnZlcnQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
