/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../app/convert/convert-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './convert.component.ngfactory';
import * as import4 from '../../../app/convert/convert.component';
class ConvertRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ConvertRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ConvertRoutingModule_1:import1.ConvertRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.ConvertComponentNgFactory],([] as any[]));
  }
  createInternal():import1.ConvertRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._ConvertRoutingModule_1 = new import1.ConvertRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          component: import4.ConvertComponent
        }
    ]];
    return this._ConvertRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ConvertRoutingModule)) { return this._ConvertRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ConvertRoutingModuleNgFactory:import0.NgModuleFactory<import1.ConvertRoutingModule> = new import0.NgModuleFactory<any>(ConvertRoutingModuleInjector,import1.ConvertRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovZ2l0aHViL2dldC1wZGYtb25saW5lL3NyYy9QcmVjaXplU29mdC5HZXRQZGZPbmxpbmUuV2ViLk5nQXBwL3NyYy9hcHAvY29udmVydC9jb252ZXJ0LXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L2dpdGh1Yi9nZXQtcGRmLW9ubGluZS9zcmMvUHJlY2l6ZVNvZnQuR2V0UGRmT25saW5lLldlYi5OZ0FwcC9zcmMvYXBwL2NvbnZlcnQvY29udmVydC1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
